name: "Construção do artefato"

on:
  push:
    branches: [ "main", "curso_2" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: go build main.go

      - name: Projeto compilado
        uses: actions/upload-artifact@v4
        with:
          name: projeto_compilado
          path: main